### PR TITLE
Feature/hounslow ch42 members area button broken

### PR DESCRIPTION
**Pull request by haider-ismail**
updated members area button url in footer and replaced with an env variable called `REACT_APP_MEMBERS_AREA_URL`

### CODE REVIEW

**Comment by AyupMike** [comment]
@haider-ismail This looks good and like that we're pulling out this link into an env. Can you also update the example env file to include this var?

**Comment by haider-ismail** [comment]
> @haider-ismail This looks good and like that we're pulling out this link into an env. Can you also update the example env file to include this var?

Good shout @AyupMike, I'll sort that out now =]

**Comment by haider-ismail** [comment]
@AyupMike  I've added the new variable to .env.example file. 

Cheers

**Comment by AyupMike** [comment]
Awesome - thanks!

**Pull request merged**
